// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upkyhkhzjswhohdosafc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwa3loa2h6anN3aG9oZG9zYWZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzAxODAsImV4cCI6MjA2ODE0NjE4MH0.JwaOtfQ-lF8PUqcHOcxnI6VdDfy7AMnIWiH1AGmDXfQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});