// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wclcvxcfcbruudqlcysk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjbGN2eGNmY2JydXVkcWxjeXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDM3NDYsImV4cCI6MjA3MDU3OTc0Nn0.e7Uhz-m4d300PiyE6YG9b-u3pthnHbofW6keSd3yiXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});